### ISSUE TITLE
Allow users to select from their own images

### ISSUE THREAD

**Issue by shealavington** [resauce-dev/directus-image-scout#1]

**Comment by maxmblack** [comment]
Thank you for this really useful extension!

Do you have any updates on this issue? It would be really cool to be able to switch between image-scout & directus file library within one field

**Comment by shealavington** [comment]
> Thank you for this really useful extension!
> 
> Do you have any updates on this issue? It would be really cool to be able to switch between image-scout & directus file library within one field

Hi @maxmblack ! I'm terribly sorry, I've not seen this till now.
I'm afraid there's no update on the status of this issue right now, I've not had the time to make the changes that I wish. I've tagged the issue with "help wanted" and if I don't get round to it, perhaps someone may have time to help-out! 

Don't get me wrong, I completely plan to get this working at some point, I just need the time :)

**Comment by shealavington** [comment]
This issue has been duplicated to [a discussion](https://github.com/resauce-dev/directus-image-scout/discussions/23) to clear the issue board 🪄 
It will be handled sometime in the future as my time is limited. The extension as-provided works for now. 🎨
