### ISSUE TITLE
Pro version (freelancer)

### ISSUE THREAD

**Issue by hermesalvesbr** [resauce-dev/directus-image-scout#17]
Hi there,

I'm looking for a extension for get product image. When I will add a new product into collection called product. When I will insert the title of product , your extension show a suggestion of 3 image product.

Do you accept to do this freelancer? I'm accept share this code with our Directus community. 

hermes at softagon.com.br

**Comment by shealavington** [comment]
> Hi there,
> 
> I'm looking for a extension for get product image. When I will add a new product into collection called product. When I will insert the title of product , your extension show a suggestion of 3 image product.
> 
> Do you accept to do this freelancer? I'm accept share this code with our Directus community. 
> 
> hermes at softagon.com.br 

Hi, unfortunately I'm not really sure what you're asking. Please do feel free to use the email from the package.json to contact me for requests. 

Closing this issue.
