### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c') and TypeError: Cannot read properties of undefined (reading 'api')

### ISSUE THREAD

**Issue by nicksergeant** [resauce-dev/directus-image-scout#19]
Kind of looks like this extension might be somewhat abandoned, but figured I'd report here just in case.

Directus 9.22.1, I was finally able to get the Image Scout interface to work as a field via:

Create Field -> Input -> Type UUID -> Continue in Advanced Mode -> Interface tab -> Delete "Input" -> Select Image Scout -> Save

That all works OK, but viewing a record in the UI throws the following JS errors from the interface:

```
runtime-core.esm-bundler.22ec0346.js:1 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.f (index.js:2:26554)
    at Jt (runtime-core.esm-bundler.22ec0346.js:1:17405)
    at dn.T [as fn] (runtime-core.esm-bundler.22ec0346.js:1:51669)
    at dn.run (runtime-core.esm-bundler.22ec0346.js:1:4937)
    at G.c.update (runtime-core.esm-bundler.22ec0346.js:1:51939)
runtime-core.esm-bundler.22ec0346.js:1 TypeError: Cannot read properties of undefined (reading 'api')
    at Proxy.getProviders (index.js:2:23494)
    at Proxy.mounted (index.js:2:26436)
    at runtime-core.esm-bundler.22ec0346.js:1:31933
```

**Comment by shealavington** [comment]
Hiya! 

I appreciate you raising this, I wouldn't say it's abandoned, but I definitely don't have the time that I wish I had! :D

It was last tested On Directus 9.18.1.
I'll see what time I can find to test this on 9.22.1 and fix it if required.

**Comment by nicksergeant** [comment]
Ah sorry about that 😅 ! Directus _has_ been moving super fast lately and making a ton of changes. If I get a few minutes today I'll try and setup the source extension files and see if I can help track it down, also 👍

**Comment by jaybharadia** [comment]
@shealavington I am also facing this same issue. Waiting for an stable update. 
Thankyou for making this extension.

**Comment by shealavington** [comment]
Hi,

@jaybharadia & @nicksergeant — I've sacrificed my evening walk to sort this out. I've tested new changes on Directus' latest version, v10.0.0 and hopefully, it's all sorted for you both now. 

I'm sorry it's not kept ahead of the curve, unfortunately, I don't have time to re-test it every time a new directus version is released, so I appreciate the issue raising and commenting.
