### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by jorge-vnarvaez** [resauce-dev/directus-image-scout#20]
When  i use any provider and find images with a prompt for example "Agriculture" and then go to the pagination and select page 2, 3, 4 or anything else the image scout field doesn't fetch new images.

**Comment by shealavington** [comment]
Hi,

Sorry, I'll need a few more details. 

Please explain what provider you're using, the search term, directus version. Perhaps even a video.

I do believe it is working, unless the network requests are failing. Are there any network errors in the network tab of the browser dev tools?

Thanks.

**Comment by jorge-vnarvaez** [comment]
Hi,

Thanks for answering me.

**Provider**

Unsplash && Pexels

**Search term**

Innovation, Agriculture

** Directus version **
10.4.3, also happens in 10.4. 2

Here's the video including the network tab log.

https://youtu.be/9iWQC3b2Cp0

**Comment by shealavington** [comment]
Thanks for that detail, I take it there's no console errors?

I'm currently away from my computer for a couple of weeks (responding on phone). I will take a look at the issue upon my return.

In the meantime, I'm open to any pull requests if you get the time yourself. 🙂

**Comment by jorge-vnarvaez** [comment]
I'm gonna check this weekend the code, I don't promise anything but I'll try to see what is the problem.

**Comment by shealavington** [comment]
Hiya @jorge-vnarvaez. 👋

I apologise for taking so long. I have a fix for this released as `Version 3.1.1`. I appreciate you taking the time to raise this and additionally, any time you may have even spent debugging yourself.

You had unfortunately raised the issue just as I was starting some back-to-back travelling and as such, for the first time in a long time I had disconnected myself from doing any coding or working. Followed by getting back into my daily job this week.

Please do give the plugin another go with the latest version and let me know how it goes.

Thanks! ✨
