### ISSUE TITLE
Error in using Unsplash

### ISSUE THREAD

**Issue by devsecur** [resauce-dev/directus-image-scout#24]
I installed the extension, added the environment variables for unsplash und CSP, added a field and tried to search for images. I get error, that no provider is available. I use directus 10.13.1

![image](https://github.com/user-attachments/assets/f10ebf48-ad7c-467c-b34e-5f9f448b6442)

![image](https://github.com/user-attachments/assets/7fcc2578-6649-44dd-8166-77ba4f085ddd)

![image](https://github.com/user-attachments/assets/061a63fb-780c-49bc-82c0-44c01db3a232)

![image](https://github.com/user-attachments/assets/8757631c-14dc-42d6-ac60-5f6f424a5695)

**Comment by shealavington** [comment]
Hi,

I'm terribly sorry for the late response. I will try to find time to take a look into this issue for you.

I cannot guarantee a timeline as I don't have the time for open source commitments that I used to have.

Hope you understand.

**Comment by shealavington** [comment]
Hi @devsecur

I'm terribly sorry for the late response. I don't have the time for open source commitments that I used to have.

Hope you understand.

Can I ask, have you ensured that you have configured the variable of `RIS_DEFAULT_PROVIDER`. Looking at your network console I can see it is attempting to use the value of `null`. This will only happen if `RIS_DEFAULT_PROVIDER` is null or unset. 

Please set this to the provider you wish to use such as `RIS_DEFAULT_PROVIDER=UNSPLASH`

I will close this issue for now, please reach back out to me if this continues.
